CREATE DATABASE Filmes;
GO

USE Filmes;
GO

CREATE TABLE Generos
(
	idGenero	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Filmes
(
	idFilme		INT PRIMARY KEY IDENTITY
	,idGenero	INT FOREIGN KEY REFERENCES Generos(idGenero)
	,Titulo		VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Usuarios
(
	idUsuario	INT PRIMARY KEY IDENTITY
	,email		VARCHAR(200) NOT NULL UNIQUE
	,senha		VARCHAR(200) NOT NULL
	,permissao	VARCHAR(200)
);